! Cisco IOS Weak Configuration
! Multiple security misconfigurations
!
hostname WeakRouter
!
enable password cisco123
!
ip http server
!
ip ssh version 1
!
snmp-server community public RO
snmp-server community private RW
!
line con 0
 no login
!
line vty 0 4
 transport input telnet ssh
 password cisco
!
interface GigabitEthernet0/0
 ip address 192.168.1.1 255.255.255.0
 no shutdown
!
end
